configuration:
  - changed-files:
      - any-glob-to-any-file:
          - 'config/**'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - '*.md'

authentication:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/auth/**'

dns:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/dns/**'

io:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/io/**'

smtp:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/smtp/**'

imap4:
    - changed-files:
        - any-glob-to-any-file:
            - 'src/imap/**'

storage:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/storage/**'

tls:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/tls/**'

github:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'